services:
  reminder:
    build:
      dockerfile: ./Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - database-reminder
    networks:
      - reminder-network

  database-reminder:
    image: "postgres:16"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "15432:5432"
    volumes:
      - database-reminder:/var/lib/postgresql/data
    networks:
      - reminder-network
volumes:
  database-reminder:

networks:
  reminder-network:
    driver: bridge