spring:
  profiles:
    active: dev
  liquibase:
    change-log: classpath*:db/changelog/db.changelog-master.yaml
    enabled: true
  application:
    name: remainder-app
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: validate
        show_sql: true
        format_sql: true
    open-in-view: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            redirect-uri: http://localhost:8081/login/oauth2/code/google
            scope: email, profile
  mail:
    host: smtp.yandex.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

scheduling:
  interval: 60000
telegram:
  bot:
    username: ${BOT_USERNAME}
    token: ${BOT_TOKEN}

url:
  api: /api/v1/reminder
  user: /api/v1/reminder/user
server:
  port: 8081

